language: android
sudo: false
jdk:
- oraclejdk8
os:
- linux
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - EMULATOR_API_LEVEL=19
  - ANDROID_ABI=armeabi-v7a
  - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - JAVA_HOME=$JAVA8_HOME
  - PWD=`pwd`
  - secure: xnzj1rSgBfWpi7mBLqss1ebkfekbxLIvj4EhNrJsVgEhHnQjZpr9C48whh+6pKbOGTgvY/IudGJydXLEWMUrFjchPcX98MWhtYbWUwX+1qkm7ifvjtsdBiDM7i62Vq57G9IELKx4Z9SHlXknQSrUAuKexudWB+mXUKFF3XUo8Nc7xoiynFgiNfcQ+HaT9OQQJJE2h/unmrHqpzz3TKdXWUJ1Dl6Ge1/QWYMrVeXFv6PWZq7W0B5Lak/K0LfDID4Qne56xvlHO1rXSs4X/+vu30K+vec4DI7znqgCs61+qMaRKxr6sTvpBvLFQ3GOM63lTiTBYO52R2W0DE48O9xzfQuSUpeEyeOrfHxSzJTZcUxHMHGIUkRBuLaf6B1H3C7YCK14o0AxB/RiYEOEzD8SAbN4d0e6Jnny5j2nKZDKbDOyDG5Xzf3HGa0DPafIdHZ54MPyrJdN4qLicZtXA5BCMEWkD5gKHqjMPRQrhdJWbM7bq+fkoDNPr73xjRSWVMqecBsj0L5PqyM1HdCdm3MZaAfJ/e2kh4vBEFbXHiPTNkTCp4BOjD6o0vYbMhIr47ZfhZ1tP9xpA1wpmv23zlLXWUNdDgm5UaX2sb7uDpj0tEFY+quKovQh3iJsBlwinahQe0ZQ7d9GZD/Qs3WCmbLofEz1+avVlCLgU808VzfC49c=
  - secure: PT0dqohiRXoPNQaIvAp6RTepXlVFhIKqVLs0q2A2IqAGEVbnErXpjSLXZLgdX7JeYl3+RptG5z0meOZCrGpjuMTutvl8VdB+YNNf+rA+P4zKxklOVYwfonb20IVYruzlq+BAEHvIWnB8XNQpXtKGzNYP81McHOECXeCEZPEk9NviGip2jf3UJ+paFkATUdufGAqmP2/jE8jlTcBX7knfqB4KrQVoMAPWMu8p+Q2zc/zVVuuuc/EL8fPTNiI9A0VfSr32WwCMsDinPOSszxsisgdJZNAA3qNJix0cht5RX8hxpld3+ymz25Cr1ZdojUt+pZPKGAClN1JZ2ErfEHBl2JCokuHgjAxWEP/HsCFU7nK5J6mNPFgz3witPNPM4AfUAcV+s7nb3V/9sylvTKkFsSXvoCUGkko6OBDlvpBj2fFQ3Xq6hANMiD9DhsB5L4z/uKYcGdAg/psT+f14J8npBI51enbzGKEI90kJ1g3NDUgem3AZaT5jJ0ulqV+Fgt4PZcKScEzF9pkObs3fNiez8PvB9uFV1tTKIiewCLNTS5t2FCSY4pEtW99tMQIOTSAAIEHAhD43ipUH+hLKF/LxnxqVkfwzLKBgfyy8faHSbUn1ElP+i5K/tHr56HMvARklUjFFbtgDPE4i5pmAhjAGxMsiH18aprq6Rlp+Gl7Zcu8=
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - platform-tools
  - tools
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license.*
  - android-sdk-license.*
install:
- git fetch --unshallow --tags
before_script:
- echo no | android create avd -f -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  -s WVGA800 -c 128M
- emulator -avd test -no-audio -no-window &
- "./gradlew clean"
script:
- echo -e '\033[0;33mBuilding...\033[0m' && echo -en 'travis_fold:start:script.build\\r'
- "./gradlew assembleRelease -PdisablePreDex"
- echo -en 'travis_fold:end:script.build\\r'
- echo -e '\033[0;33mUI tests...\033[0m' && echo -en 'travis_fold:start:script.uitest\\r'
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0
- adb shell settings put global transition_animation_scale 0
- adb shell settings put global animator_duration_scale 0
- adb shell input keyevent 82 &
- adb logcat -c
- echo -en 'travis_fold:end:script.uitest\\r'
before_deploy:
- openssl aes-256-cbc -K $encrypted_33b0d72ee996_key -iv $encrypted_33b0d72ee996_iv -in wgplaner_signed_apk_keystore.jks.enc -out wgplaner_signed_apk_keystore.jks -d
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/wgplaner_signed_apk_keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk wgplaner_android_signed_apk_key
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk WGPlaner.apk"
deploy:
  provider: releases
  file: WGPlaner.apk
  skip_cleanup: true
  on:
    repo: WGPlaner/wg_planer
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "CnUJV7iKOwA+BHP3/DpPDUuvpiXtwrYj5ZoQ5XukpyZNFf3ZEC2qzUIxz1cd6q7A2VB3mmQjazA3OAjcTM8GQ6ovwbRaD+SJVCbvp2DPgGLVaTAkDEwR4Uxtny26VKzMmOQIQFXcOlMJC7xph1kx/C2qBaRIz2E3Vf81RgV5jL9jS3yiJzU7gSkv6PeqzcuETn9gyUrA0K74FTjdLl+CwLOYM4xsHEIv9/a4R5mKFwe0xIPflmV3Rxx/1RcSOlcezC6XMOJVIIpe3L9ZqSRB2zAYUD1zSgFVnMpNT6oqsXP23IBInnIcKzfhV+JUgXmLismZ3FxWDkTco7tD52i8ZNrytCSVpQGRWA+zM6foOJTURMKPjX5QNkXDgmQVxEqcaMkGj/Ppbfdba1aAPBkVw1cI4AXqrDwEbJcZAMCm9MxjrIG39bljOOJw5SOXntmieFI1j5VmPbEJnXFlUBvtju1ocThIhYXFBtLll04I7/MtgrAX/n0NOj8k94NybFGf8s5z97TaU8HPU/5V0Iv9GopMMf4X8uo6SP6QOEMrGJPcLRQDfYaNwXGm6aJGncOQ+7SZwt08vnkjhZTH/6bPykPVmajZBrE3TMDPzOWGIGrG0vi14Ph4wPEv1WZ+n+5FYW+GctgPDJzVgScHfaPFXcX7SEORzN1T6TU5Es5pdLI="
