language: android
sudo: false
jdk:
- oraclejdk8
os:
- linux
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - EMULATOR_API_LEVEL=19
  - ANDROID_ABI=armeabi-v7a
  - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - JAVA_HOME=$JAVA8_HOME
  - PWD=`pwd`
  - secure: kXPldTDvPorfZIDdQk3NQ/6chlNYuW8rHPczwjX/FbUL73+N0Wo0ytZHn0ZFNwERAMZwalx/R/8S80Hih3hOvPMEhgw7pB5MPaL2mzO5H2JqdyBmC+pcJhswSXz8dFnoffejzOYEZdz5tZmHjjxhhwwFalX1noqSF0fHWPKUMvn59x2YRLi4tuNsnRQqaSep8PqbSATY5xvUEQoLjW+hwc1Y+/nPG+xDYVaKH3/YyNdq/0dppyl8WTSomHIA6w/yY/5xcztNRQpDDWgkSmZUdCkjSbdCu6xmjcdKJ3XpiA4RvsAnG0mrf6n8zsqVapE65kTy79x90+0giwKexOyzgiP9TvwZ12P7HAfk2NFQAasFhblqF5103yCM7+8CAhuWuAEYqGVlI0BQjDki8NvHPGEjfFwfghUlOEqiLTygS+SkDLl9KOJKRysQQa2I9E7IyMJJDsqH/42tbQVu82bDk7M7EnvVbmjlNzkntzmilD7FSAGr8B0IhPgypO6Fyq1VdiLiLiDAyOl5r19ffQfJchbCQMtbFVTtjMXB37ca9jezOvsbAK8hOfPstitZthxkAOu4K4oP3e5qyDxmN60WVV0XdiUZqtI6ThHkr9HOl2U4bnFNVEqDdyNwXF6I1j7jiIcjrFS4qbcpZ2h3pFhbAd8z92hYB1I7QQrEBcgc/jM=
  - secure: jt+4JvMeXIsrixL1ibHWhBTfUkDvphSw+0yPeq1vL4NhrBSR4wqcQ3l6UFsZU/8GE/1ZVjHieE/BjzGh4P49NJUdvkVhJTUThn4nOEDldMe7bPvNPWp3gcnLixArXyyObsDv7mKx0hc9bmXsDWDGHvyMEwhA/pTswdk8noLERZlGhATUB9ZpW7Gi28YwA6VVbslhyqoGU0UuwzakdgvK5I2foddgiX6pTMRX4E5uIYMQkEbn5sSoZX/S65/TmsZW49vNBM6/JXUufFbGDi7bHKIGlqqkNvTcSWIdgwXU9zJ5CLLuyNsH0Bjv/n7cX3v/2rg0c+qvgEHILA6TEwz7rb0Vx/We8m9zEIMIK2mYDRtZR7OqKUgtvKVP9MMwP8YFxtNT/Qg5K4RT/DimC7FDeg2cBfMN2OmMe+0USofXufP/nY/8/dWJabKx6OQmEVd/5yva07h3iZvD4vrMMB5vI3UW9Kinh5yeRwCtqGwuCd8wHdt6g7jiD/FqfY79uOV3A8D1pLlC4IjCQdMCPQcRTpDTVbUqeklAY23U9RrHWc8kOq1OONaLqfzcmTOqUE241ZtV3dSYDfBGq0N35vA28kjPbf5Kml50YfRqF7g0zftwIT/PmjUY1rpD30/rR2sTvTbzMF806PdXCD2T9WbJMIH6fZlgR38kddu/4JAzZmk=
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - platform-tools
  - tools
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license.*
  - android-sdk-license.*
install:
- git fetch --unshallow --tags
before_script:
- echo no | android create avd -f -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  -s WVGA800 -c 128M
- emulator -avd test -no-audio -no-window &
- "./gradlew clean"
script:
- echo -e '\033[0;33mBuilding...\033[0m' && echo -en 'travis_fold:start:script.build\\r'
- "./gradlew assembleRelease -PdisablePreDex"
- echo -en 'travis_fold:end:script.build\\r'
- echo -e '\033[0;33mUI tests...\033[0m' && echo -en 'travis_fold:start:script.uitest\\r'
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0
- adb shell settings put global transition_animation_scale 0
- adb shell settings put global animator_duration_scale 0
- adb shell input keyevent 82 &
- adb logcat -c
- echo -en 'travis_fold:end:script.uitest\\r'
before_deploy:
- openssl aes-256-cbc -K $encrypted_33b0d72ee996_key -iv $encrypted_33b0d72ee996_iv
  -in wgplaner_signed_apk_keystore.jks.enc -out wgplaner_signed_apk_keystore.jks -d
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/wgplaner_signed_apk_keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk key0
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/zipalign -v 4 app-release-unsigned.apk WGPlaner.apk"
deploy:
  provider: releases
  file: WGPlaner.apk
  skip_cleanup: true
  on:
    repo: WGPlaner/wg_planer
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: CnUJV7iKOwA+BHP3/DpPDUuvpiXtwrYj5ZoQ5XukpyZNFf3ZEC2qzUIxz1cd6q7A2VB3mmQjazA3OAjcTM8GQ6ovwbRaD+SJVCbvp2DPgGLVaTAkDEwR4Uxtny26VKzMmOQIQFXcOlMJC7xph1kx/C2qBaRIz2E3Vf81RgV5jL9jS3yiJzU7gSkv6PeqzcuETn9gyUrA0K74FTjdLl+CwLOYM4xsHEIv9/a4R5mKFwe0xIPflmV3Rxx/1RcSOlcezC6XMOJVIIpe3L9ZqSRB2zAYUD1zSgFVnMpNT6oqsXP23IBInnIcKzfhV+JUgXmLismZ3FxWDkTco7tD52i8ZNrytCSVpQGRWA+zM6foOJTURMKPjX5QNkXDgmQVxEqcaMkGj/Ppbfdba1aAPBkVw1cI4AXqrDwEbJcZAMCm9MxjrIG39bljOOJw5SOXntmieFI1j5VmPbEJnXFlUBvtju1ocThIhYXFBtLll04I7/MtgrAX/n0NOj8k94NybFGf8s5z97TaU8HPU/5V0Iv9GopMMf4X8uo6SP6QOEMrGJPcLRQDfYaNwXGm6aJGncOQ+7SZwt08vnkjhZTH/6bPykPVmajZBrE3TMDPzOWGIGrG0vi14Ph4wPEv1WZ+n+5FYW+GctgPDJzVgScHfaPFXcX7SEORzN1T6TU5Es5pdLI=
